import "./css/globals.css";
import { Inter, Architects_Daughter } from "next/font/google";

import Navbar from "./components/navbar/Navbar";
import ChatWidget from "./components/ChatWidget";
import ClientOnly from "./components/ClientOnly";
import ToasterProvider from "./providers/ToasterProvider";

import LoginModal from "./components/modals/LoginModal";
import RegisterModal from "./components/modals/RegisterModal";
import getCurrentUser from "./actions/getCurrentUser";
import Footer from "./components/footer/footer";

import { headers } from "next/headers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const architects_daughter = Architects_Daughter({
  subsets: ["latin"],
  variable: "--font-architects-daughter",
  weight: "400",
  display: "swap",
});

export const metadata = {
  title: "More",
  description: "Generated by create next app",
};
export const Example = {
  parameters: {
    nextjs: {
      appDirectory: true,
    },
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();
  const headersList = headers();
  const header_url = headersList.get("x-url") || "";
  console.log(header_url);
  if (
    header_url === "http://localhost:3000/" ||
    header_url === "http://more.website/"
  ) {
    return (
      <html lang="en">
        <body className={`${inter.variable} ${architects_daughter.variable}`}>
          <ClientOnly>
            <ToasterProvider />
            <LoginModal />
            <RegisterModal />
            <Navbar currentUser={currentUser} />
            <ChatWidget />
          </ClientOnly>
          <div className="font-inter antialiased bg-gray-900 text-gray-200 tracking-tight">
            {children}
            <Footer />
          </div>
        </body>
      </html>
    );
  } else {
    return (
      <html lang="en">
        <body>
          <div className="w-screen h-screen">{children}</div>
        </body>
      </html>
    );
  }

  // return (

  // );
}
